### ISSUE TITLE
got 404 Not Found while installing

### ISSUE THREAD

**Issue by vk-rpp** [CraigCottingham/react-leaflet-graticule#1]
Hi

Installing a package via npm install I have the error 
npm ERR! 404 Not Found: react-leaflet-graticule@latest

How can I install it? Thanks

**Comment by krisalyssa** [comment]
I've been away from this for more than a year (as you probably noticed), and I don't remember why there isn't a 0.1.0 release on npmjs.com.

I'll try to make some time soon to figure out where it's at and get a release out. However, there's a good chance that an existing project from someone who knows React and Leaflet better than I do will work for you better and sooner, like

* https://www.npmjs.com/package/react-leaflet-gars-graticule
* https://www.npmjs.com/package/react-leaflet-mgrs-graticule

**Comment by krisalyssa** [comment]
Duplicated by #2 .
